### ISSUE TITLE
Gadfly v1.4.0 ?

### ISSUE THREAD

**Issue by Brinkhuis** [JuliaRegistries/General#102758]
I installed Gadfly in a (new) Julia environment. The package manager status command shows it’s version v1.4.0. However, on [https://gadflyjl.org/stable 16](https://gadflyjl.org/stable) the latest version is v1.3.4. Where can I find the v1.4.0 documentation and/or the change log?

![Screenshot 2024-03-12 at 19 34 22](https://github.com/JuliaRegistries/General/assets/3044985/83c4a588-e129-4546-b7f7-b44a6802ebf2)

**Comment by DilumAluthge** [comment]
You should open this issue on the https://github.com/GiovineItalia/Gadfly.jl repo.
