### ISSUE TITLE
Recommend for, or at least against, some OSI licences? E.g. against Apache 2.0

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaRegistries/General#106420]
I believe we require to be on the OSI list, but not all there are good e.g. not Apache 2.0, since not GPL 2.0 compatible (and I'm seeing one such package being registered, not the first one).

https://www.gnu.org/licenses/license-list.html#apache2

https://www.apache.org/licenses/GPL-compatibility.html

I'm not sure we can or should forbid it (retroactively), but we could recommend against it, and not auto-merge it.

Rather recommend its:

https://spdx.org/licenses/LLVM-exception.html

(or some other alternative). I don't actually see that modifier on the OSI list, but seems implied it's ok, at least we can explicitly allow it as the alternative and recommend. Some on OSI list are superseded, e.g. Apache 1.1, so also recommend (maybe forbid?) those:

https://opensource.org/license/page/4?ls=Apache

Short-list to approve (in that order...):
MIT
CC-0 [more similar?]
MPL 2.0
Apache-LLVM
LGPL 2.1
LGPL 3.0
GPL 2.0
GPL 3.0
[what more? AGPL]

and only allow licenses that are compatible with above, i.e. last two, at least for auto-merging.

[Some would recommend against GPL 3.0 AND GPL 2.0, since GPL 3.0 kind of broke 2.0.. but I'm not sure we can go into that now. Is there a good alternative with same goals, compatible with both? EUPL 1.2?]

https://commission.europa.eu/content/european-union-public-licence_en

https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12

Some more are interesting and ok, e.g:
https://opensource.org/license/bsdpluspatent

We currently do not allow non-open-source, such as business license, such as SSPL, and I'm not pushing for that, rather think we should oppose, or at least needs to be a separate discussion:

https://redis.io/about/license/

https://thenewstack.io/linux-foundation-forks-the-open-source-redis-as-valkey/

[I'm not sure other almost open source apply here, such as for Llama, I think only about weights, and for such data, may or may not be ok. Maybe data in general, with (otherwise) open source code, can be distributed with under just a redistributable license or e.g. CC-NC?]

**Comment by DilumAluthge** [comment]
Let's keep things as simple as possible. If it's an OSI-approved license, then we allow it. If it's not an OSI-approved license, then we don't allow it.

I don't see the point in having any complexity beyond that.

**Comment by PallHaraldsson** [comment]
Even if we don't change automerging rule, we can document, I can make a PR of recommended, and not, licenses.
