### ISSUE TITLE
Is it possible to remove a package ?

### ISSUE THREAD

**Issue by j-fu** [JuliaRegistries/General#11604]
Hi,  I registered VTKView.jl , which will have several serious binary dependencies which will take some time to become stable. So I continue to develop the package complex in my own registry. The idea is to transfer things here at a certain point of time. In order to avoid confusion I think it would be better to remove it here. Would this be possible ?

**Comment by DilumAluthge** [comment]
We generally do not allow you to delete packages from the general registry.

**Comment by DilumAluthge** [comment]
It is perfectly fine to work on the package in your own registry, and then, whenever you are ready, start making releases again in the General registry.

There's no need to delete the package.

**Comment by j-fu** [comment]
Ok then that's what I'll do.
