### ISSUE TITLE
Protocol about repo name matching directory name

### ISSUE THREAD

**Issue by djsegal** [JuliaRegistries/General#11712]
@ChrisRackauckas, this is related to: https://github.com/JuliaRegistries/General/commit/dea440dfa11a59d9d3c522eb504f650cdf7fc6f2

This is the first project where the repo name doesn't match the directory name. I realize that the project was a rename fork, but it might screw up bots in the future?

**Comment by DilumAluthge** [comment]
Make a copy of the repository. Have one repo that is FiniteDiff.jl, and have the other repo be called DiffEqDiffTools.jl

The FiniteDiff package will use the FiniteDiff.jl repo.

The DiffEqDiffTools package will use the DiffEqDiffTools repo.
