### ISSUE TITLE
Un-registering package?

### ISSUE THREAD

**Issue by Zymergen-phaverty** [JuliaRegistries/General#11732]
I'd like to move GenomicVectors.jl over to BioJulia. How might I un-register it here?

**Comment by PallHaraldsson** [comment]
You can't delete a package (see #11604) but you can move it under a new umbrella. I've seen PRs to this registry doing so. I'm not sure, but it seems you just you manually make such a PR here. Not sure there's functionality in the Pkg, i.e. from the REPL.

**Comment by DilumAluthge** [comment]
You cannot unregister a package.

If you move the package to a different Git organization, make a PR to update the URL.
