### ISSUE TITLE
Registrator pull request not merged in General

### ISSUE THREAD

**Issue by arismavridis** [JuliaRegistries/General#117548]
Hello,

A few days ago I [submitted a package via registrator](https://github.com/JuliaRegistries/General/pull/117170), but I realised there were a couple of bugs. 
I left a comment to stop the registration, and restarted it after fixing the bugs, using the same version tag. 
For some reason, the pull request has not been approved four days later. 

Would there be something to do manually in this case, or  is it  just a matter of waiting more? 
Is it a bug or a feature of registrator?

**Comment by DilumAluthge** [comment]
https://github.com/JuliaRegistries/General#automerge-is-blocked-by-one-of-my-comments-how-do-i-unblock-it

**Comment by arismavridis** [comment]
Thanks a lot Dilum, didn't notice that!
