### ISSUE TITLE
Remove package GAPTypes.jl ? What happens if I delete the repository

### ISSUE THREAD

**Issue by fingolfin** [JuliaRegistries/General#11874]
So I've seen a few closed issues here that say you can't unregister a package.

Well, I was just about to delete the repository https://github.com/oscar-system/GAPTypes.jl but then I realized it's still registered here, wanted to unregister it, then found those closed issues.

But what actually will happen if I delete that repository? The reasons for that is that the GAPTypes package always was a nasty hack to make the package `GAP.jl` work; and we finally luckily figured out a way to do without it. Yet people still find the repository and get confused by it, so I want to remove it. But if I do so, I wonder what are the consequences...

But of course I also want to be a good Julia citizen... so I thought I should ask here on how to proceed.

**Comment by fredrikekre** [comment]
Nothing will really happen, the package is cached in various places so we can replace it. Why not just use githubs archive feature and leave it there?

**Comment by PallHaraldsson** [comment]
>a nasty hack to make the package GAP.jl work

A. If that package works I would mention it in the Readme file at/for GAPTypes, i.e. change there "If you want to use GAP.jl, please use this package"

B. One other possible option: Change that package to a dummy empty package with a dependency on GAP.jl? I'm not sure if that applies for those using, is something more would be involved. Not mutually exclusive with A.

**Comment by DilumAluthge** [comment]
Seems like this has been answered.
