### ISSUE TITLE
please advise on package name

### ISSUE THREAD

**Issue by tpapp** [JuliaRegistries/General#1221]
I am about to convert [skeleton.jl](https://github.com/tpapp/skeleton.jl), a script that generates package skeletons, to a package itself, and plan to register it.

Should I 

1. just capitalize to `Skeleton`,
2. consider keeping the lowercase `skeleton`,
3. or change to something more descriptive, eg `PkgSkeleton`?

(I hope it is OK to ask things like this here, would prefer to make these decisions now instead of after a registration attempt).

**Comment by StefanKarpinski** [comment]
I would probably go with `PkgSkeleton` but I think that `Skeleton` might also be fine if you want a cute name. Are you're aware of https://github.com/invenia/PkgTemplates.jl?

**Comment by tpapp** [comment]
Thanks for the advice. I went with PkgSkeleton.jl.

Yes, I am aware of PkgTemplates.jl, this is a more KISS-style approach.
