### ISSUE TITLE
Link posted by GitHub action broken

### ISSUE THREAD

**Issue by AlfTetzlaff** [JuliaRegistries/General#12800]
In case the guidelines for auto merging are not met and there is an issue with compatibility specification, the bot posts a link to

https://julialang.github.io/Pkg.jl/v1/compatibility/

which should instead link to

https://julialang.github.io/Pkg.jl/v1/compatibility   (.html)

=> delete trailing /

**Comment by fredrikekre** [comment]
Please reopen at the Pkg.jl repo.
