### ISSUE TITLE
Created new release, registry still shows the previous one

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaRegistries/General#1410]
FinEtools: release at v3.0.0, registry has v2.0.1.
https://github.com/PetrKryslUCSD/FinEtools.jl/releases

Perhaps the repo is not set up correctly with Julia Team Registrator? This is what I have:
![image](https://user-images.githubusercontent.com/9855832/59566187-47812300-9011-11e9-85fe-dd8ee258a716.png)

**Comment by fredrikekre** [comment]
Creating GitHub releases is not how you trigger the bot, please have a look at the README: https://github.com/JuliaRegistries/Registrator.jl

**Comment by PetrKryslUCSD** [comment]
Sorry, I forgot. Thanks for your help.
