### ISSUE TITLE
Add README with basic documentation?

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaRegistries/General#1626]
This could clarify both 
- what the General registry is, how one is expected to interact with it as a package developer (i.e. Registrator, optionally TagBot, but also you can make PRs to edit files directly)
- how to do a few things beyond tagging a new release e.g. how do I rename a package? How do I "blacklist" a version?

**Comment by nickrobinson251** [comment]
could also point to https://julialang.github.io/Pkg.jl/v1/registries/

and maybe the things mention in the second bullet point above actually belong on that page?

**Comment by StefanKarpinski** [comment]
Sure, seems like a good idea.

**Comment by ericphanson** [comment]
I made a PR with some basic docs here: https://github.com/JuliaRegistries/General/pull/3567. I was more focused on giving explanations for common “waiting for author” holds, from what I’ve seen looking at registrator PRs, than blacklisting and things like that though (which I don’t actually know how to do).

**Comment by DilumAluthge** [comment]
Can we add a link in the README to https://github.com/JuliaRegistries/RegistryCI.jl? And maybe we can have a note saying that to report issues with automerge, please open an issue in the RegistryCI.jl repo (not the General registry repo)?

**Comment by DilumAluthge** [comment]
Fixed by #6335. 

Of course, we can (and should) continue to expand and improve the README, see e.g. #3567
