### ISSUE TITLE
Registry appears broken for Julia 1.0

### ISSUE THREAD

**Issue by krrutkow** [JuliaRegistries/General#18]
As of the last commit (65950254d2fbf791c3fbb2fd4207662d4ab8c824  @StefanKarpinski ) performing an update in the package manager results in `Unsatisfiable requirements detected for package ...` for nearly all packages.
For anybody encountering this, I was able to git checkout the General repository at the commit before it and it now functions as expected.

**Comment by StefanKarpinski** [comment]
It's reverted now.
