### ISSUE TITLE
JuliaRegistrator thinks my repo URL changed

### ISSUE THREAD

**Issue by fonsp** [JuliaRegistries/General#18996]
Today it told me 
> Error while trying to register: Changing package repo URL not allowed, please submit a pull request with the URL change to the target registry and retry.

https://github.com/fonsp/Pluto.jl/commit/9128eadec331a6d6be76b5d3e20d4b7b9559f882#commitcomment-41194335

But I did not change the repository URL.

What should I do?

**Comment by fredrikekre** [comment]
Perhaps best to wait until https://discourse.julialang.org/t/pkg-downtime-incident/44288 has been resolved.

**Comment by fonsp** [comment]
Thanks!
