### ISSUE TITLE
Error: can no longer update package versions

### ISSUE THREAD

**Issue by yossibokor** [JuliaRegistries/General#18997]
I addressed some issues in a package of mine, a received the following from @JuliaRegistrator:
`Error while trying to register: Changing package repo URL not allowed, please submit a pull request with the URL change to the target registry and retry.`
I assume this is related to #18991.

**Comment by DilumAluthge** [comment]
Package registrations are temporarily disabled due to a breaking change in the GitHub API.

More details are available here: https://discourse.julialang.org/t/pkg-downtime-incident/44288
