### ISSUE TITLE
Cap older versions breaking everything?

### ISSUE THREAD

**Issue by galenlynch** [JuliaRegistries/General#20]
I've been pulling my hair out the past two hours because all of a sudden packages will not update, install, resolve, remove, anything...

I keep getting this error when using Pkg3:
`restricted by julia compatibility requirements to versions: uninstalled — no versions left`

When I inspected the `Compat.toml` of the offending packages, I saw that indeed, packages which had been working on 0.7/1.0 were now only accepting julia 0.6.

Then I noticed the most recent commit 0c75a4d9bd1f8d8386216a008792cbf6d105345e, which made this change, intentionally?

So what am I supposed to do? I can no longer use the package manager. Am I not using pkg3 correctly, or is this a bug?

**Comment by galenlynch** [comment]
If I checkout the last commit before 0c75a4d9bd1f8d8386216a008792cbf6d105345e, then I can use the package manager again.

**Comment by StefanKarpinski** [comment]
What are you trying to install? Without that information, we can't fix it.

**Comment by galenlynch** [comment]
Here are the packages that didn't work before I gave up: Decimals, ShowItLikeYouBuildIt, Destruct, Seaborn, TOML, PkgDev, but it felt like the tip of the iceberg. If I somehow got around one unsatisfiable dependency, it would just reveal another.

**Comment by KristofferC** [comment]
Do these work on 0.7?

**Comment by StefanKarpinski** [comment]
I'm able to `dev Decimals` and then `test Decimals` but it does print a lot of deprecation warnings.

**Comment by galenlynch** [comment]
I'm not sure if PkgDev did (I don't think it did), but Destruct and Seaborn certainly did. Looking at the released versions for the others, Decimals seems to have a release explicitly for 1.0 support, TOML seems like a maybe, ShowItLikeYouBuildIt seems doesn't have a version about compatibility.

I don't know, I've been using 0.7 for a month or more now without any problems, but now I can't. The only thing I tried to add this morning when I discovered the problem was JLD2, which I think is 1.0 compatible.

**Comment by StefanKarpinski** [comment]
* `ShowItLikeYouBuildIt` fails tests on 0.7 and 1.0 so that's a legitimate cap.
* `Seaborn` is broken and needs to use `Test` instead of `Base.Test`.
* `Destruct` also has deprecations in its tests.
* etc.

In short, I think the answer to this is people need to fix their shit. I'm still perplexed that people are so unwilling to just fix a few deprecations, but now is the time to do so. If you want to work around this while people get their acts together and fix things and make releases of packages that aren't broken, you can go into `~/.julia/registries/General` and do
```sh
git checkout -b dontcapmebro e5748a7e36745cf42952c5451586a79911a524b4
```

**Comment by galenlynch** [comment]
It might be true that people need to fix their packages, but as a user yesterday Julia worked, and today it doesn't. 

I thought the point of 0.7 was that it was 1.0 with deprecation warnings instead of failure. Maybe you could change the enforced cap to include 0.7?

**Comment by galenlynch** [comment]
Dunno, I'll gladly switch to 1.0 once the packages I need to graduate stop throwing deprecation warnings. Until then, 0.7 it is.

Not that I get a vote, but if I did I would vote for relaxing the cap to allow minimally maintained, but still useful, packages to work and be installable on 0.7.

**Comment by timholy** [comment]
I can verify that there was a problem but that 1a5454cf434439087e8a0e8b98f64293cb42aaec seems to have resolved the test I was about to report.

**Comment by galenlynch** [comment]
Thanks for relaxing the cap, it makes life much easier!

**Comment by StefanKarpinski** [comment]
Sure, happy to make life easier while still having correct caps for 1.0 at least.
