### ISSUE TITLE
Heads-up: Migrating JuliaPOMDP solver packages to General

### ISSUE THREAD

**Issue by zsunberg** [JuliaRegistries/General#20728]
Hi All, Just wanted to give a heads up that we are going to migrate all of the POMDP solver packages from the [JuliaPOMDP Registry](https://github.com/JuliaPOMDP/Registry) to this General registry (JuliaPOMDP/POMDPs.jl#303). There are many packages that have acronym names, which is one of the reasons we had our own registry - hopefully this will not be a huge problem. We think it is better to have them in the General registry.

The plan is to keep old versions in the JuliaPOMDP registry, but register all new versions only in General. My understanding is that Pkg will merge the versions of packages with the same UUID so that people can use both registries seemlessly if they want.

The first instance is DiscreteValueIteration: https://github.com/JuliaRegistries/General/pull/20727

It looks like we will need people to help us manually merge the packages since they will not meet the initial version requirements. Who should I contact to help us out with that?

If anyone has any comments or suggestions on this, please let us know!

CC: @MaximeBouton @rejuvyesh

**Comment by DilumAluthge** [comment]
If you need manual merges, feel free to post in the `#pkg-registration` channel on Slack!

**Comment by DilumAluthge** [comment]
Let me know if you run into any problems!
