### ISSUE TITLE
a new UUID is generated even if there is a Project.toml with an existing one

### ISSUE THREAD

**Issue by tpapp** [JuliaRegistries/General#22]
Even if a package has a Project.toml with an `uuid` field, a new (apparently random, unrelated) one seems to be generated by the pipeline.

It would be nice to just use the existing one.

Cf [discussion](https://discourse.julialang.org/t/different-uuid-in-project-toml-and-registry/15819)

**Comment by timkittel** [comment]
How is the process here? While certainly not being high-prio, it would be nice if it were solved.

**Comment by StefanKarpinski** [comment]
There is a solution: if you are registering a package in METADATA, then you should use the utility function `Pkg.METADATA_compatible_uuid` to generate a UUID for your project, e.g.:
```
julia> Pkg.METADATA_compatible_uuid("MyPkg")
UUID("793ebe2b-975c-555a-bd0c-65619c3a03ab")
```

**Comment by timkittel** [comment]
Oh, nice, thanks!

**Comment by tpapp** [comment]
I think the issue was closed a bit prematurely, for two reasons:

1. `Pkg.METADATA_compatible_uuid` is a workaround, not solution, and then it is not easily discoverable. A user could just set up a `Project.toml` by just reading the relevant manuals (Julia's docs, Pkg docs, etc) and never learn about it, running into the issue only when registering the package (and then it is pretty insidious, as mismatching UUIDs can give surprising behavior when one is unaware that this is a possibility).

2. I still don't understand why the registry has to do this. I understand that historically, packages had no UUIDs so one had to be generated, but that is becoming less and less common.

**Comment by StefanKarpinski** [comment]
The issue is in the wrong place, first off—there's no code here. Once we switch the registration process to registering directly with the General registry then this won't be an issue any more. So the solution to this problem is to implement https://github.com/JuliaLang/Pkg.jl/issues/849.
