### ISSUE TITLE
about missing Deps.toml file for the package

### ISSUE THREAD

**Issue by wookay** [JuliaRegistries/General#23]
Hello, just registered a package and now it has automatic sync with METADATA.

The package contains [Project.toml](https://github.com/wookay/Jive.jl/blob/v0.1.0/Project.toml) with
```
[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
```

but in the following registry doesn't have the `Deps.toml` file for that package.
https://github.com/JuliaRegistries/General/tree/master/J/Jive
```
Compat.toml
Package.toml
Versions.toml
```

I don't know how could I make the `Deps.toml` file.
It's best appreciate for any hint.
thanks.

**Comment by StefanKarpinski** [comment]
The only released version of Jive doesn't have any dependencies:

https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/Jive/versions/0.1.0/requires

If you want `Test` in the `Deps.toml` file, you need it in the REQUIRE file. Currently, the project's `Project.toml` file is ignored and what's registered in METADATA is the source of truth, which is based on the REQUIRE file not the Project.toml file.

**Comment by wookay** [comment]
thank you very much!

**Comment by wookay** [comment]
I'm sorry to bother it again,
when I added `Test` to the `REQUIRE` file, I got failed on travis-ci for METADATA.jl.

https://travis-ci.org/JuliaLang/METADATA.jl/jobs/474972602#L506
```
ERROR: LoadError: package Jive v0.1.1 requires a non-registered package: Test
Stacktrace:
 [1] check_metadata(::Set{String}) at /home/travis/build/JuliaLang/METADATA.jl/.test/METADATA.jl:266
 [2] check_metadata() at /home/travis/build/JuliaLang/METADATA.jl/.test/METADATA.jl:262
 [3] top-level scope at none:0
 [4] include at ./boot.jl:317 [inlined]
 [5] include_relative(::Module, ::String) at ./loading.jl:1044
 [6] include(::Module, ::String) at ./sysimg.jl:29
 [7] include(::String) at ./client.jl:392
 [8] top-level scope at none:0
in expression starting at /home/travis/build/JuliaLang/METADATA.jl/.test/METADATA.jl:279
The command "sh .test/ci.sh" exited with 1.
```

**Comment by StefanKarpinski** [comment]
Ah yes, sorry, since `Test` is a stdlib you can't depend on it in REQUIRE. The sync script uses a regular expression to detect stdlib dependencies, I'm not sure why it's picking this one up.

**Comment by StefanKarpinski** [comment]
This was actually a bug in the registry sync script. It's fixed now. Sorry for the trouble and thanks for bringing it to my attention!

**Comment by wookay** [comment]
your welcome! I'm closing the issue with happy.
