### ISSUE TITLE
Cannot sync with latest version

### ISSUE THREAD

**Issue by thautwarm** [JuliaRegistries/General#24]
I've released the new version for about 2 days, while the synchronization haven't been performed yet.

The repo is at https://github.com/thautwarm/MLStyle.jl

**Comment by KristofferC** [comment]
One of

https://github.com/JuliaLang/METADATA.jl/pull/20781
https://github.com/JuliaLang/METADATA.jl/pull/20786
https://github.com/JuliaLang/METADATA.jl/pull/20824

needs to be merged first.

**Comment by StefanKarpinski** [comment]
Seems that the package had an incorrect UUID. See the CI logs for those registration PRs.
