### ISSUE TITLE
Patach release not merged in General registry

### ISSUE THREAD

**Issue by aorchini** [JuliaRegistries/General#24252]
Hi all,

A few days ago I have submitted a patch release of the package WavesAndEigenvalues via the JuliaRegitrator. No issues were detected for automerge, still the patch release is pending in the General pull requests list since days now. My previous experience was that patch releases were taking less than an hour to be accepted, has something changed? 

Thanks

**Comment by fredrikekre** [comment]
Your comment without [noblock] is blocking it.

**Comment by aorchini** [comment]
Sorry for that, I though the comment without [noblock] was connected to a previous registration request, in which automorege failed. Thanks for taking care of this.
