### ISSUE TITLE
Workflow dispatch trigger for TagBotTriggers

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/General#24662]
If the TagBotTriggers cron job fails, it would be nice if I could just re-trigger it with a workflow dispatch. But I'm not sure how `RegistryCI.TagBot` would response to a workflow dispatch event.

@christopher-dG

**Comment by christopher-dG** [comment]
Yeah, I was meaning to do this myself actually. All that needs to be added is for [this line](https://github.com/JuliaRegistries/RegistryCI.jl/blob/master/src/TagBot/cron.jl#L1) to include `"workflow_dispatch"` I think.
