### ISSUE TITLE
DeIdentification package missing from registry

### ISSUE THREAD

**Issue by mcmcgrath13** [JuliaRegistries/General#25]
DeIdentification was registered a couple months ago ([PR](https://github.com/JuliaLang/METADATA.jl/pull/19915)), but hasn't synced to the General registry.  Is there something incorrect with the package that I need to fix?

**Comment by StefanKarpinski** [comment]
It seems to have a number of stdlibs in the REQUIRE file which it shouldn't have.

**Comment by mcmcgrath13** [comment]
Thanks @StefanKarpinski ! I pushed a new release and it's working now.
