### ISSUE TITLE
failure in Pkg.resolve() after removal of list of Julia versions

### ISSUE THREAD

**Issue by s2maki** [JuliaRegistries/General#25233]
revision b1c163f103 is causing failure in Pkg.resolve()

```
(ADVISE) pkg> resolve
 Resolving package versions...
ERROR: The following package names could not be resolved:
 * julia (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```

**Comment by fredrikekre** [comment]
What Julia version? Can you include the content of `Project.toml` and `Manfest.toml`?

**Comment by s2maki** [comment]
Julia 1.3.1
[Project.toml](https://github.com/JuliaRegistries/General/files/5590736/Project.toml.txt)
[Manifest.toml](https://github.com/JuliaRegistries/General/files/5590740/Manifest.toml.txt)

**Comment by fredrikekre** [comment]
Can that be reduced? In particular, there seems to be ~20 or so local paths in the Manifest. Do you have any idea where `julia` might be referenced in the packages here?

**Comment by s2maki** [comment]
To the best of my knowledge, none of our Manifest or Project files includes any reference to Julia.  Third-party Project files do refer to it, but those are outside of our control.

I will see if I can strip it down further to determine one package that's the cause.

**Comment by fredrikekre** [comment]
> Third-party Project files do refer to it, but those are outside of our control.

Okay, but how do the refer to it? The only valid place to refer to it should be in the `[compat]` section, but I can't reproduce this error using trivial examples.

**Comment by s2maki** [comment]
Got it.  The problem was in the fact that we were pinned to an older version of Mux.jl that didn't have a Project file in it at all.  It had a REQUIRE file that referred to a specific Julia version range.

So there's two things to consider.  One that we need to update our Mux version to eliminate the problem on our end.  Thanks for pushing me in the direction that helped me figure this out.  The second is that there still may be Julia 1.0 users (LTS) that refer to packages that don't have TOMLs in them.  For those users, reverting the change would be necessary.

@KristofferC has done the revert.  I will update my pin of Mux so that I can tolerate the change to the Registry.  I'll leave it up to the Julia devs whether or not the revert should stand.

Thanks much!

**Comment by KristofferC** [comment]
Thanks for looking into it!
