### ISSUE TITLE
installing MAT Pkg

### ISSUE THREAD

**Issue by shashikdm** [JuliaRegistries/General#26]
![screenshot from 2019-02-02 15-31-57](https://user-images.githubusercontent.com/30661008/52162861-cf6c2d80-26ff-11e9-86be-0e87be2b3e74.png)
![screenshot from 2019-02-02 15-32-22](https://user-images.githubusercontent.com/30661008/52162862-cf6c2d80-26ff-11e9-8b57-4cf68ce1cac7.png)
incorrect files are installed in the .julia directory when using Pkg.add("MAT")
I had to clone https://github.com/JuliaIO/MAT.jl and replace the file in .julia/packages directory in order to get it to precompile successfully and work.

**Comment by StefanKarpinski** [comment]
This appears to be a bug with the MAT package.
