### ISSUE TITLE
Changing repo link for official packages 

### ISSUE THREAD

**Issue by RGerzaguet** [JuliaRegistries/General#26397]
Hello there,

I have 2 registered packages (DigitalComm.jl and UHDBindings.jl) that have been moved from my personal Github repo to another one (JuliaTelecom group) in order to increase the visibility regarding telecommunication stuff in Julia.
However, I cannot update the package anymore (as it points to the old repo). Juliaregistrator tells me that `Error while trying to register: Changing package repo URL not allowed, please submit a pull request with the URL change to the target registry and retry.` but I don't know where to do this and how.
The kink update are 
- DigitalComm is now here : https://github.com/JuliaTelecom/DigitalComm.jl
- UHDBindings is now here: https://github.com/JuliaTelecom/UHDBindings.jl
So any help is welcome here !
Thanks in advance
BR
@+R

**Comment by fredrikekre** [comment]
Can you make a PR to update the URLs?

**Comment by fredrikekre** [comment]
See https://github.com/JuliaRegistries/General#how-do-i-transfer-a-package-to-an-organization-or-another-user

**Comment by fredrikekre** [comment]
https://github.com/JuliaRegistries/General/pull/26407
