### ISSUE TITLE
TagBot trigger cron job keeps failing

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/General#27670]
The TagBot triggers cron job keeps failing because of the bug when trying to open fixup PRs.

@christopher-dG Could we put the "fixup PR" code inside a try-catch block, just for now? Otherwise, once an error is thrown, all the remaining repos get skipped because Julia exits with an error.

**Comment by christopher-dG** [comment]
Yeah, feel free. Sorry I haven't gotten the time to fix that.

**Comment by DilumAluthge** [comment]
No rush. The try-catch should tide us over for now.

**Comment by DilumAluthge** [comment]
Will be fixed by https://github.com/JuliaRegistries/RegistryCI.jl/pull/321
