### ISSUE TITLE
Post a reminder message on stale PRs, instead of just closing

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/General#28236]
In this example (https://github.com/JuliaRegistries/General/pull/26570), the stale bot posted a message and then closed the PR immediately.

Instead of doing that, I think it would be better to first post a reminder message, then wait a little while, and then close the PR if nobody responds after the reminder message.

Is that possible?

cc: @giordano @fredrikekre

**Comment by giordano** [comment]
That's what I did initially in #26710.
