### ISSUE TITLE
Registration has no effect

### ISSUE THREAD

**Issue by aminya** [JuliaRegistries/General#28687]
I recently registered [CompileBot](https://github.com/aminya/CompileBot.jl) 1.0.6, in the following PR, but it seems it is not done!

https://github.com/JuliaRegistries/General/pull/28685

The proof:
```julia
julia> using Pkg; Pkg.add( PackageSpec(name = "CompileBot", version = "1") );
   Updating registry at `C:\Users\aminy\.julia\registries\General`
  Resolving package versions...
Updating `C:\Users\aminy\.julia\environments\v1.5\Project.toml`
  [877fb49a] + CompileBot v1.0.5
Updating `C:\Users\aminy\.julia\environments\v1.5\Manifest.toml`
  [877fb49a] + CompileBot v1.0.5
  [f68482b8] + Cthulhu v1.6.1
  [48062228] + FilePathsBase v0.9.7
  [1eca21be] + FoldingTrees v1.0.1
  [6b79fd1a] + GitHubActions v0.1.3
  [aa65fe97] + SnoopCompile v2.5.0
  [e2b509da] + SnoopCompileCore v2.5.0
  [ddb6d928] + YAML v0.4.6
```

Blocks https://github.com/JuliaPlots/Plots.jl/pull/3247

**Comment by fredrikekre** [comment]
It takes some time for it to propagate to the servers.

**Comment by aminya** [comment]
How long does it take? The PR was merged 4 hours ago.

**Comment by DilumAluthge** [comment]
Duplicate of https://github.com/JuliaRegistries/General/issues/16777

**Comment by DilumAluthge** [comment]
You can follow the discussion in https://github.com/JuliaRegistries/General/issues/16777
M
