### ISSUE TITLE
New package versions in METADATA are not propagated into the registry

### ISSUE THREAD

**Issue by Datseris** [JuliaRegistries/General#29]
As Chris (and others) have mentioned, the registry is currently broken. New package versions are not installable. I noticed this with [MusicManipulations](https://github.com/JuliaLang/METADATA.jl/pull/21283) which was tagged days ago but still not installable on Travis or anywhere else. Other authors, e.g. DiffEq, Measurements.jl have the same problem.

**Comment by Datseris** [comment]
P.s.: If this is an easy fix, I would sooooo much appreciate it being done before Wednesday. A **DynamicalSystems.jl** introductory video is broadcasted in the official JuliaLang youtube channel, and it would be kind of bad for users to not be able to install the latest versions (which have some crucial fixes).

**Comment by nalimilan** [comment]
FWIW, you can always install a package directly from git with `]add https://github.com/JuliaMusic/MusicManipulations.jl.git`

**Comment by Datseris** [comment]
Ah!!!! Nice! I though this was possible by only using `dev`. Alright I will say that in the start of the tutorial then! 

But wait. What does this do if the package is already installed? Does it override the stable installed version with the current state of the master branch? Because this is what I would need. I know `dev` does it.

**Comment by nalimilan** [comment]
Yes, it uses master by default. You can also do `]add https://github.com/JuliaMusic/MusicManipulations.jl.git#v0.6.0` if you want a specific version.

**Comment by thautwarm** [comment]
I have the same problem. Installing via direct link seems to be not that robust.
Users could fetch preview versions unexpectedly.

**Comment by StefanKarpinski** [comment]
Fixed by https://github.com/JuliaLang/METADATA.jl/pull/21342.

**Comment by dehann** [comment]
Hi, i have been having issues with regular attobot style updates not making it through to General registry either.  ApproxManifoldProducts.jl, IncrementalInference.jl.

**Comment by StefanKarpinski** [comment]
Yup, already fixed, like I wrote.
