### ISSUE TITLE
Warning: Some registries failed to update: — registry detached

### ISSUE THREAD

**Issue by walra356** [JuliaRegistries/General#29551]
I am trying to use the TagBot:
Registering package: CamiXon
Repository: https://github.com/walra356/CamiXon.jl
Created by: @walra356
Version: v1.1.1
Commit: efc06810293e914552f423f29b6fba84fbf0b0b5
Reviewed by: @walra356
Reference: walra356/CamiXon.jl@efc0681#commitcomment-46849885

The automerge does not work, it fails after a warning: 

[ Info: Attempting to `import` the package
     Copying registry from `~/work/General/General`
       Added registry `General` to `/tmp/jl_YVIDjr/registries/General`
[ Info: Attempting to `Pkg.add` package...
    Updating registry at `/tmp/jl_YVIDjr/registries/General`
┌ Warning: Some registries failed to update:
│     — `/tmp/jl_YVIDjr/registries/General` — registry detached
└ @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:1220

I removed the general registry, even reinstalled julia from scratch  but it does not resolve the problem.
please advice me.

**Comment by fredrikekre** [comment]
That warning is expected since the tests run with the pr branch checked out. I don't think that is what is causing the failure. Do you have a link?

**Comment by walra356** [comment]
Thank you for having a look! 
https://github.com/JuliaRegistries/General/pull/29548

**Comment by walra356** [comment]
Then I guess it has to do with skipping a version. But how to work with an earlier commit (v1.1.0) if I loose the required addition of the compat data (which I tried to fix in going to the version 1.1.1). Puzzling. I stumble into this repeatedly but cannot find the proper procedure.

**Comment by DilumAluthge** [comment]
@christopher-dG

**Comment by fredrikekre** [comment]
I am not sure what you mean. Why can't you register 1.1.0?

**Comment by walra356** [comment]
I tried before to register version v1.1.0 but that was rejected with the message given below. 

┌ Error: Dependency "FITSIO" does not have a compat entry that has an upper bound
└ @ RegistryCI.AutoMerge ~/.julia/packages/RegistryCI/6RREe/src/AutoMerge/guidelines.jl:61
┌ Info: Compat (with upper bound) for all dependencies
│   meets_this_guideline = false
└   message = "The following dependencies do not have a `[compat]` entry that is upper-bounded and only includes a finite number of breaking releases: FITSIO"
┌ Info: If it is a patch release, then it does not narrow the Julia compat range
│   meets_this_guideline = true
└   message = ""

etc,

After this my reaction was to run the CompatHelper fro Github Actions. This removed the compatibility issue but and I tried to register the result as v.1.1.1. This resulted in the message that I skipped a version. So I went back to the previous commit and met again the objection printed above. Thanks for your support.

**Comment by walra356** [comment]
So, how can I correct commit, after it is rejected? You cannot undo a commit is it?

**Comment by fredrikekre** [comment]
> tried to register the result as v.1.1.1.

Right, but since 1.1.0 was never released you should just keep that version number.

**Comment by walra356** [comment]
Yes, but when I did the @registrator register() comment. I got the message that that version number belonged to a different commit. The commit where I corrected the compatibility issue.

**Comment by walra356** [comment]
Going back to that to that commit I was stuck again with the compatibility issue. I do something stupid, butt what?

**Comment by walra356** [comment]
I looked up the message:

Error while trying to register: "Tag with name v1.1.0 already exists and points to a different commit"
So how to change a file after it is rejected by the TagBot?

**Comment by walra356** [comment]
Sorry, it must be something elementary but I cannot find this in the documentation.

**Comment by walra356** [comment]
OK I have to delete the old tag. Do the correction on the commit and trigger the registration. I am not yet fully on top but start to get the point. Thanks.
