### ISSUE TITLE
OpenCL

### ISSUE THREAD

**Issue by marsupialsoup** [JuliaRegistries/General#30]
Hello, there is a version of OpenCL which is compatible with Julia version > 0.7.0 (i.e. 1.0.0, and 1.1.0). Is the version that the package manager install specified here? Pkg now only get those earlier versions, where there are syntax changes that breaks it.

**Comment by StefanKarpinski** [comment]
Please post questions to the [Julia discourse](https://discourse.julialang.org/c/user) discussion forum.
