### ISSUE TITLE
change ApproxFun{Base,Fourier} bounds?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaRegistries/General#306]
@dlfivefifty, these bounds on your packages look suspicious:
```
A/ApproxFunBase/Compat.toml
32-["0.0.4"]
33:julia = "0.7-1.1"

A/ApproxFunFourier/Compat.toml
27-["0.0.2-0"]
31:julia = "0.7-1.1"

A/ApproxManifoldProducts/Compat.toml
14-["0.0.2-0"]
16:julia = "0.7-1.1"
```
Can you confirm or deny that these should be changed to `0.7-1`?

**Comment by dlfivefifty** [comment]
I don't know where those came from: I'm using `julia = 0.7, 1.0` which I assumed would be `0.7-2.0-`:

https://github.com/JuliaApproximation/ApproxFunBase.jl/blob/master/Project.toml

**Comment by StefanKarpinski** [comment]
Are all of those versions compatible with 1.1, 1.2, etc.? If so, I'll make a PR to fix this.

**Comment by fredrikekre** [comment]
I think they got in when Registrator was bugged, e.g. https://github.com/JuliaRegistries/General/pull/199#discussion_r277590788

**Comment by StefanKarpinski** [comment]
Note that ApproxManifoldProducts did not, it was introduced earlier: 50f9d5f7010da2b3405525ce2004bcce730e3fc4. It may be legit.

**Comment by dlfivefifty** [comment]
Well 1.2, 1.3, etc. don't exist yet, but I assume they will be compatible. (This assumption may of course be wrong: for example, some older versions worked in Julia v1.0 but not in Julia v1.1 due to change in the behaviour of `lmul!`. ) 

I don't recognize "ApproxManifoldProducts".

**Comment by StefanKarpinski** [comment]
Ok, I just guessed that anything with the word "Approx" in it was yours 😁

**Comment by StefanKarpinski** [comment]
Indeed, the cap there seems intentional, although I'm not sure why:

https://github.com/JuliaRobotics/ApproxManifoldProducts.jl/blob/master/REQUIRE

**Comment by dlfivefifty** [comment]
I wouldn't bother correcting it for ApproxFun*. I'm about to tag a version `0.1`, and worrying about old `0.0.x` versions not working in 1.2 does not seem a good use of your time.

**Comment by StefanKarpinski** [comment]
I'm fixing all the incorrect bounds that were introduced by this bug, so it's all the same to me.
