### ISSUE TITLE
Compat.toml lists "0.10" before "0.2"

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaRegistries/General#334]
This is a fairly minor issue but in, for example, 

https://github.com/JuliaRegistries/General/blob/master/A/ApproxFun/Compat.toml  

the versions "0.10.x" are listed before "0.2.x", which is slightly confusing.

**Comment by StefanKarpinski** [comment]
The solution is to change TOML to print keys in natural sort order by default. This isn't really the place for that issue though—you could open it on Pkg.jl instead since that's where the embedded copy of TOML that we use lives (for now).

**Comment by dlfivefifty** [comment]
Moved: https://github.com/JuliaLang/Pkg.jl/issues/1176
