### ISSUE TITLE
Drop 0.7 compatibility from JSON v0.21

### ISSUE THREAD

**Issue by tlnagy** [JuliaRegistries/General#3440]
The latest version of JSON.jl was tagged, but it's broken on Julia 0.7 ([ref](https://github.com/JuliaIO/JSON.jl/pull/285#issuecomment-497425740)) yet it still lists support for Julia 0.7 in its compat section here: https://github.com/JuliaRegistries/General/pull/2060/files#diff-68074356855d5796422b09f38b90317fR41. This has caused failures for us over on `Compose.jl` and `Gadfly.jl` ([ref](https://travis-ci.org/GiovineItalia/Gadfly.jl/jobs/583375273))

Can this be fixed retroactively such that Julia 0.7 support is dropped from JSON v0.21?

**Comment by fredrikekre** [comment]
```
pkg> add JSON@0.21

pkg> test JSON
```
passes tests on Julia 0.7 though?

**Comment by tlnagy** [comment]
Running the same command locally on 0.7 passes so not sure what is going on. Apologies for the spurious issue. I'll close it for now and reopen if I figure out why this is happening.
