### ISSUE TITLE
PR Failing due to compatibility upper bounds committed by bot

### ISSUE THREAD

**Issue by Omastto1** [JuliaRegistries/General#35640]
Hi, 
I would like to register a new version of `PointBasedValueIteration.jl`, but the PR is failing.

The JuliaRegistrator bot committed changes to `Compat.toml` which in my opinion could cause the upper bound comp failure.
The bot committed this change:
```
["0.2-0"]
FiniteHorizonPOMDPs = "0.3"
POMDPModelTools = "0.3.2-0.3"
POMDPPolicies = "0.3-0.4"
```
(https://github.com/JuliaRegistries/General/pull/35637/commits/3a9d7007d56a89f68bd5f8845a616f5fbb9be5d6)

Is this an error that I can solve on my side? How?

**Comment by fredrikekre** [comment]
You are just missing `[compat]` for `Distributions` (as the [message](https://github.com/JuliaRegistries/General/pull/35637#issuecomment-829202372) suggests).
