### ISSUE TITLE
Proposal: rename `/A/`, `/B/`, etc. to `/packages/A/`, `/packages/B/`, etc.

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/General#36948]
Currently, the General registry has top-level directories of the form `/A/`, `/B/`, etc. And then e.g. the package `Example` has the files `/E/Example/Package.toml`, etc.

However, this means that when you go to https://github.com/JuliaRegistries/General, the first thing you see is a really long list of directories, and you have to scroll down quite a bit before you even get to the README.

I'd like to propose that we rename `/A/`, `/B/`, etc. to `/packages/A/`, `/packages/B/`, etc.. And then e.g. the package `Example` will have the files `/packages/E/Example/Package.toml`, etc.

Here is a screenshot of what the General registry home page would look like with this change (taken from https://github.com/JuliaRegistries/General/tree/dpa/move_letter_directories_to_subdirectory):

![Screen Shot 2021-05-17 at 23 37 03](https://user-images.githubusercontent.com/5619885/118586942-a4d7fe80-b769-11eb-8a1d-ad069b7c50a9.png)

I think that this is much more readable, and it allows users to get to the README quicker and easier.

This should not be a breaking change, since any consumer of the General registry should be reading the package paths from the `Registry.toml` file.

**Comment by findmyway** [comment]
For those who downvoted this suggestion, could you explain a little bit why?

Personally I think this is quite useful for first time contributors. Back to the first time I learn to register my first Julia package, I just simply @JuliaRegistrator and wait the PR to be merged. But I really didn't know that there were a lot of important guidelines in the README part. (sorry there are so many folders in the root dir and I thought this repo is just some auto-generated/maintained one). And I only know them later when someone shared the link on slack.
