### ISSUE TITLE
Can I retract a package?

### ISSUE THREAD

**Issue by singularitti** [JuliaRegistries/General#38623]
[`EquationsOfState.jl`](https://github.com/MineralsCloud/EquationsOfState.jl) was a package that I wrote to do equation of state fitting. However, later I completely rewrite this code into a new package [`EquationsOfStateOfSolids.jl`](https://github.com/MineralsCloud/EquationsOfStateOfSolids.jl). The functionalities of `EquationsOfState.jl` is fully covered by `EquationsOfStateOfSolids.jl` already, so I want to deprecate the former. I want to reserve this name for future packages (e.g., a package that covers `EquationsOfStateOfGases.jl`, etc.). Is it possible that I retract this package from `General`?

**Comment by fredrikekre** [comment]
[No](https://github.com/JuliaRegistries/General#how-do-i-remove-a-package-or-version-from-the-registry).
