### ISSUE TITLE
Change url repo of package EnKF

### ISSUE THREAD

**Issue by mleprovost** [JuliaRegistries/General#4121]
Hello, 

I would like to change the url of the package EnKF.jl (reference of the pull request https://github.com/JuliaRegistries/General/pull/2801) to:
https://github.com/mleprovost/EnKF.jl   but I can't do it with Registrator

Best,

**Comment by fredrikekre** [comment]
You can create the pull request for that yourself without registrator.

**Comment by mleprovost** [comment]
Sorry, this is the first time I register a package. 
I understand that I should make a pull request, but I don't really know how to do it. Should I download JuliaRegistries, modify the file in EnKF to update the url of the file and then make a git push origin master?

**Comment by Nosferican** [comment]
The registry works like any other repository (no magic behind it). Fork the repository, make a new branch and commit the changes to it. After pushing it to the remote, GitHub will ask you whether you want to make a PR (select from yourfork branch to JuliaRegistries/General). The maintainers will review and can accept/commit it.
