### ISSUE TITLE
Duplicate package remains at old version

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaRegistries/General#41567]
For, at least, MCMCChains there exists also an older registered version namely MCMCChain (without s). 

MCMCChain is linked to https://github.com/TuringLang/MCMCChain which is automatically redirected to https://github.com/TuringLang/MCMCChain.

This, lets call it, old package `MCMCChain` is not updated by `JuliaRegistrator`, but still available for users. Users who install `MCMCChain` get version 0.2.3, whereas MCMCChains is at 4.13.1. Also, the old package shows up as breaking in the nanosoldier report: https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/e04e3e1_vs_96386f9/report.md.

So, this is unfortunately confusing for developers and users. Is there a good way to solve this at the TuringLang side, or is this something that could be solved in JuliaRegistries/General?

**Comment by rikhuijzer** [comment]
@KristofferC

**Comment by DilumAluthge** [comment]
We had the same issue for StatPlots versus StatsPlots.

What I did (https://github.com/JuliaRegistries/General/pull/39292) was to cap StatPlots to <= Julia 1.6. The result of this is:
1. For people using Julia <= 1.6, no effect.
2. For people using Julia >= 1.7, and using a `Manifest.toml` file, no effect.
3. For people using Julia >= 1.7, but not using a `Manifest.toml` file, it won't let them install StatPlots. So this prevents people from doing e.g. `Pkg.add("StatPlots")` on Julia >= 1.7.

I'd recommend we do the same here.

cc: @giordano

**Comment by KristofferC** [comment]
Capping the julia compat seems reasonable if the package doesn't work on later julia versions.
