### ISSUE TITLE
Untracked packages in General registry

### ISSUE THREAD

**Issue by bmharsha** [JuliaRegistries/General#4683]
Following folders (And the relevant toml’s) are present in the registry, but the relevant package entry is not present in Registry.toml , so users cannot install these packages

* Arduino = https:/github.com/JuliaRegistries/General/tree/master/A/Arduino
* Chunks = https:/github.com/JuliaRegistries/General/tree/master/C/Chunks
* ControlCore = https:/github.com/JuliaRegistries/General/tree/master/C/ControlCore
* DotOverloading = https:/github.com/JuliaRegistries/General/tree/master/D/DotOverloading
* DynamicalBilliardsPlotting = https:/github.com/JuliaRegistries/General/tree/master/D/DynamicalBilliardsPlotting
* GetC = https:/github.com/JuliaRegistries/General/tree/master/G/GetC
* GLUT = https:/github.com/JuliaRegistries/General/tree/master/G/GLUT
* KeyedTables = https:/github.com/JuliaRegistries/General/tree/master/K/KeyedTables
* LazyCall = https:/github.com/JuliaRegistries/General/tree/master/L/LazyCall
* LazyContext = https:/github.com/JuliaRegistries/General/tree/master/L/LazyContext
* LazyQuery = "https:/github.com/JuliaRegistries/General/tree/master/L/LazyQuery"
* NanoTimes = https:/github.com/JuliaRegistries/General/tree/master/N/NanoTimes
* OnlineMoments = "https:/github.com/JuliaRegistries/General/tree/master/O/OnlineMoments"
* OpenGL = "https:/github.com/JuliaRegistries/General/tree/master/O/OpenGL"
* OrthogonalPolynomials = https:/github.com/JuliaRegistries/General/tree/master/O/OrthogonalPolynomials
* Parts = https:/github.com/JuliaRegistries/General/tree/master/P/Parts
* PhasedArrayTracking = https:/github.com/JuliaRegistries/General/tree/master/P/PhasedArrayTracking
* ProjectiveDictionaryPairLearning = https:/github.com/JuliaRegistries/General/tree/master/P/ProjectiveDictionaryPairLearning
* React = https:/github.com/JuliaRegistries/General/tree/master/R/React
* RecurUnroll = https:/github.com/JuliaRegistries/General/tree/master/R/RecurUnroll
* RequirementVersions = "https:/github.com/JuliaRegistries/General/tree/master/R/RequirementVersions"
* SDL = https:/github.com/JuliaRegistries/General/tree/master/S/SDL
* SessionHacker = https:/github.com/JuliaRegistries/General/tree/master/S/SessionHacker
* SimilarReferences = https:/github.com/JuliaRegistries/General/tree/master/S/SimilarReferences
* Sparrow = https:/github.com/JuliaRegistries/General/tree/master/S/Sparrow
* StringArrays = https:/github.com/JuliaRegistries/General/tree/master/S/StringArrays
* TypedBools = https:/github.com/JuliaRegistries/General/tree/master/T/TypedBools
* ValuedTuples = https:/github.com/JuliaRegistries/General/tree/master/V/ValuedTuples
* ZippedArrays = https:/github.com/JuliaRegistries/General/tree/master/Z/ZippedArrays

**Comment by KristofferC** [comment]
I think all of these packages have had their repository removed but the script I ran to remove pre 1.0 packages must have handled that incorrectly. All of these folder can be removed.

**Comment by bmharsha** [comment]
I've sent following PR https://github.com/JuliaRegistries/General/pull/4717 to fix this issue.
