### ISSUE TITLE
CI fails for Nightly build of Julia due to compat requirement for OpenBLAS

### ISSUE THREAD

**Issue by Azzaare** [JuliaRegistries/General#47158]
It is not blocking, but CI fails for Nightly build of Julia when I registered packages today. It comes from compat requirements of OpenBLAS

```
ERROR: Unsatisfiable requirements detected for package OpenBLAS_jll [4536629a]:
 OpenBLAS_jll [4536629a] log:
 ├─possible versions are: 0.3.17 or uninstalled
 └─restricted to versions 0.3.13 by an explicit requirement — no versions left
```

Can be found in #47157 and #47155 (at least)

**Comment by IanButterworth** [comment]
Could it be that the manifest was generated by an older julia version?

**Comment by fredrikekre** [comment]
A resolve fail too, yes. The manifest is this one: https://github.com/JuliaRegistries/General/blob/master/.ci/Manifest.1.8.toml

**Comment by KristofferC** [comment]
I think https://github.com/JuliaLang/Pkg.jl/blob/master/src/HistoricalStdlibs.jl needs to be kept in sync with master. Not sure.

**Comment by IanButterworth** [comment]
> "just download the toml files and instantiate" might modify things, right?

Actually, it wont. The Pkg.precompile that's called by `Pkg.instantiate` currently doesn't re-resolve. Only when `Pkg.precompile` is explicitly called
