### ISSUE TITLE
Manual PR for non-github repository?

### ISSUE THREAD

**Issue by cgeoga** [JuliaRegistries/General#49803]
Hello---I'd like to register a [package](https://git.sr.ht/~cgeoga/GPMaxlik.jl) that I don't have hosted on github or gitlab. The documentation on registrator strongly suggests letting that service make automated PRs, but using the web version doesn't support anything besides github or gitlab, and the github app obviously only supports github.

Looking at the auto-generated PRs, it doesn't seem like it would be impossible to manually put together an appropriate one for this non-github/lab hosted package. Would something like that possibly be accepted after review, or is that something that is very unlikely to be acceptable?

If unacceptable, I would appreciate any guidance on registering the non-github/lab package. I understand that it's annoying, but nothing about the actual registration process appears github-dependent to me, and I like diversity in code hosting platforms. So if there is any way to add my package to the general registry I'd be very interested.

Thanks in advance for the help/discussion. Apologies also if I've missed some discussion about this---I have looked around, but it is possible that there is a resource with information on this topic that I've missed.

**Comment by fredrikekre** [comment]
You can use https://github.com/GunnarFarneback/LocalRegistry.jl to generate the diff and then make the PR. Alternatively you can have a mirror on github/gitlab and register from there.

**Comment by cgeoga** [comment]
Thanks so much for the fast and helpful reply. I'll give both of those a look and hopefully make something work.
