### ISSUE TITLE
How to change the name of a package?

### ISSUE THREAD

**Issue by ericqu** [JuliaRegistries/General#49849]
Is there a procedure to follow to change the name of a package?

I released the package LinearRegression (https://github.com/ericqu/LinearRegression.jl); however, there is another package with the same name already registered. I will think of a new name, but I wonder how to change the name in practice (without creating troubles latter)? 
Can I register the package with a different name so that the users can still keep their `using LinearRegression`, or does the registered package name need to be the same?

**Comment by DilumAluthge** [comment]
https://github.com/JuliaRegistries/General/blob/master/README.md#how-do-i-rename-an-existing-registered-package
