### ISSUE TITLE
IsURL.jl is no longer there

### ISSUE THREAD

**Issue by singularitti** [JuliaRegistries/General#50661]
I just found that [`IsURL.jl`](https://github.com/zlatanvasovic/IsURL.jl) is no longer there. @zlatanvasovic, is that an unfortunate accident? If so, is it possible for you to move it back? Thank you!

**Comment by zlatanvasovic** [comment]
I wanted to delete another repository and not that one. 🙄 Thanks for noticing, restored it!
I also see your projects are using it, I'm glad it found its use :smile:
