### ISSUE TITLE
trouble with upgrading LinearRegressionKit.jl to a new version

### ISSUE THREAD

**Issue by ericqu** [JuliaRegistries/General#51334]
I am trying to push version 0.7.4 of LinearRegressionKit.jl. Version 0.7.3 is already registered. 

When I try to register version 0.7.4 I get the error message: 
> Please update the version number in the package's Project.toml before registering a new version. The current version number is already tagged to a different commit.

I then tried to move directly to version 0.7.5 because I did not know how to solve the message.
I did not get an immediate error message, but there was an issue in the merge:
> Does not meet sequential version number guideline: version 0.7.5 skips over 0.7.4

So I now reverted to version 0.7.4 with a new tag: **v0.7.4REDO**. Edit: I made another tag: **v0.7.4+REDO** as I wasn't sure if the plus sign was important or not.
Obviously, I get the first error message again. 
How / what can I do to resolve the first error message?

**Comment by DilumAluthge** [comment]
Delete the `v0.7.4` tag from your repository, and then register

In general, we don't recommend creating the tag until after the General registry PR has been merged.

You can use Julia TagBot for this purpose.

**Comment by ericqu** [comment]
Thanks!
@DilumAluthge is there a doc/web page that summarizes the recommendations? I would like to get better at this.
