### ISSUE TITLE
Package not registered after 5 days

### ISSUE THREAD

**Issue by Sushant-Padha** [JuliaRegistries/General#52110]
I created a package called [TimetableSolver.jl](https://github.com/Sushant-Padha/TimetableSolver.jl), and registered it using [Registrator](https://juliahub.com/ui/Registrator).

There was in issue with the installation (issues with dependencies and compatibility) which took me two attempts to solve, then I re-registered the package, and this time all the checks succeeded.

However, its been 5 days since I uploaded a working version, but it still hasn't been registered. Here is the pull request #51762 .

I believe it may be because of the comments I made on the pull request, causing the bot to not automerge. But, these comments were made when my package was genuinely broken and since then, has been fixed. Are those comments still interfering with the automerge? If yes, how do I fix it?

**Comment by DilumAluthge** [comment]
Edit all of your comments, and add the text `[noblock]` anywhere in each of the comments.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaRegistries/General/blob/master/README.md#automerge-is-blocked-by-one-of-my-comments-how-do-i-unblock-it
