### ISSUE TITLE
Error while trying to register: Changing package repo URL not allowed

### ISSUE THREAD

**Issue by YongHee-Kim** [JuliaRegistries/General#54893]
I've changed the repo address from https://github.com/JuliaRegistries/General/pull/51694

But couldn't update package https://github.com/YongHee-Kim/XLSXasJSON.jl/commit/4b188a5fb6e2c99f66d9b077de05ba75271389af#comments

Nothing seems wrong to me. Could you help me find the fix?

**Comment by fredrikekre** [comment]
Probably you used the wrong capitalization in https://github.com/JuliaRegistries/General/pull/51694?

**Comment by YongHee-Kim** [comment]
Sorry about my mistake. I've made another PR to correct this

**Comment by YongHee-Kim** [comment]
[JuliaRegistrator](https://github.com/JuliaRegistrator) works fine now https://github.com/JuliaRegistries/General/pull/55189 
thank you 😄
