### ISSUE TITLE
Cryptic error thrown when "_" included in repository name

### ISSUE THREAD

**Issue by alex-s-gardner** [JuliaRegistries/General#57208]
Registering my first package I got the following cryptic error thrown by AutoMerge.run:

```
Error: Some registries failed to update:
│     — `/tmp/jl_Mc2e8U/registries/General` — registry dirty
└ @ Pkg.Registry /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Pkg/src/Registry/Registry.jl:450
```

After a bunch of searching and digging I realized that my package name was non-conforming and included an underscore ("_") in the package name. 

I realize that the correct naming convention is detailed here: https://juliaregistries.github.io/RegistryCI.jl/stable/guidelines/#Automatic-merging-guidelines

But I missed the only "**alphanumeric characters**" in my first skim of the document

I wonder if a check could be added for basics things like conforming package names and that a [compat] list is included in the .toml file... this would make it easier for non-observant people like me to trace issues with first-time package registration... then again, maybe it's good to have a bit of a barrier to keep lazy readers like me from registering a package ;-)

**Comment by DilumAluthge** [comment]
The list of issues found by AutoMerge is posted in the AutoMerge comment, e.g. https://github.com/JuliaRegistries/General/pull/57187#issuecomment-1076869924
