### ISSUE TITLE
Pkg.update() does not return latest version

### ISSUE THREAD

**Issue by walra356** [JuliaRegistries/General#57722]
The JuliaTagBot automerged CamiXon v.1.5.10 and v1.6.0. This correctly is reflected by the Package page on Github and the documenter but for an unkown reason the Pkg.update() sticks to v.1.5.9. I am not aware of changing any settings locally. 

Can you advise me?

_Originally posted by @walra356 in https://github.com/JuliaRegistries/General/issues/57708#issuecomment-1084940299_

**Comment by fredrikekre** [comment]
Works for me
```shell
$ pkg add CamiXon@1.6 &> /dev/null && pkg st | rg CamiXon
  [e90a53f3] CamiXon v1.6.0
```
I guess you have an outdated registry for some reason.

**Comment by walra356** [comment]
Thank you. I will search in this direction.
