### ISSUE TITLE
Weaken auto-merge criteria on sequential versioning

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaRegistries/General#5812]
I was slightly surprised that I tagging new patches for previous versions is not auto-merged, e.g., tagging v0.6.1 after v0.7:

https://github.com/JuliaRegistries/General/pull/5751

This seems like a very "normal" situation where, for whatever reason, older versions need to be maintained, in fact Julia does it as well (v1.0.5 tagged after v1.1 for example). This isn't the case for me, but one could imagine that this might arise from security bug fixes, in which case rapid merging would be ideal.

I'd propose changing auto-merge to allow for older tags, perhaps under the condition that the tag is on a separate branch to `master`, e.g., the tag above was on the branch `release-0.6`.

**Comment by fredrikekre** [comment]
It's a bug; https://github.com/JuliaRegistries/RegistryCI.jl/issues/49
