### ISSUE TITLE
offline install

### ISSUE THREAD

**Issue by pxiaomin** [JuliaRegistries/General#58937]
I want to install the following package from github. I tried offline install
First, I download with  git clone https://github.com/JuliaRegistries/General.git

when I add ./General in REPL.
But I get the following error,
could not find project file in package at `../../registries/General` maybe `subdir` needs to be specified

**Comment by DilumAluthge** [comment]
The issue tracker is for reporting bugs.

Please ask questions on Julia Discourse: https://discourse.julialang.org/
