### ISSUE TITLE
PkgServer synchronization

### ISSUE THREAD

**Issue by ufechner7** [JuliaRegistries/General#59568]
I updated my package [GitHub - ufechner7/KiteModels.jl: Kite and tether models for the simulation of kite power systems](https://github.com/ufechner7/KiteModels.jl) to version 0.3.3 10 hours ago, but if I do:

```
mkdir tmp
cd tmp
julia --project="."
using Pkg
Pkg.add("KiteModels")
```

I still get version 0.3.2.

Is the package server infrastructure for Europe (NL) broken?

**Comment by ufechner7** [comment]
OK, now it is update... 

Thanks!

**Comment by tpgillam** [comment]
Possibly related to: https://github.com/JuliaLang/Pkg.jl/issues/3137
