### ISSUE TITLE
Automerge version dilemma

### ISSUE THREAD

**Issue by Rratic** [JuliaRegistries/General#59872]
In my case, I registered with the version "1.0.0-alpha" (which is not banned)
But currently I can do nothing since
In RegisteryCI https://github.com/JuliaRegistries/RegistryCI.jl/blob/bc393c7522d785fe501812ed36f0fd41119f6022/src/AutoMerge/guidelines.jl#L425 it calls `diff = difference(old_version, new_version)`, and function difference is in https://github.com/JuliaRegistries/RegistryCI.jl/blob/bc393c7522d785fe501812ed36f0fd41119f6022/src/AutoMerge/semver.jl#L9 it throws an error if i'm trying to register "1.0.0"
It also stops me from trying to register "1.1.0" , it would tell me `Does not meet sequential version number guideline: version 1.1.0 skips over 1.0.0`

[my 1.0.0 pull](https://github.com/JuliaRegistries/General/pull/59724)
[my 1.1.0 pull](https://github.com/JuliaRegistries/General/pull/59869)

**Comment by giordano** [comment]
> In my case, I registered with the version "1.0.0-alpha" (which is not banned)

It _is_ banned but automerge didn't catch it because of bug, addressed by https://github.com/JuliaRegistries/RegistryCI.jl/pull/450.
