### ISSUE TITLE
Twitter announce action is failing

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaRegistries/General#61034]
https://github.com/JuliaRegistries/General/actions/workflows/announce.yml

It looks like it is unhappy with the YAML on line 12, which is the logic for checking the label

**Comment by logankilpatrick** [comment]
@ericphanson any suggestion on this?

**Comment by ericphanson** [comment]
Yes, I put up https://github.com/JuliaRegistries/General/pull/61026 a few hours ago :). Should've requested your review though.
