### ISSUE TITLE
Failed to update DuckDB package after change of ownership

### ISSUE THREAD

**Issue by Mytherin** [JuliaRegistries/General#62710]
Hey everyone, after the successful change of ownership of the DuckDB package in #58361 (thanks again for all the help!), I have been trying to upload a new version of the DuckDB package. See [here](https://github.com/duckdb/duckdb/commit/f8c5b215d860506f37d2bd5b49013f172752916d#commitcomment-76514219) for the comment that was supposed to trigger the update. However, it does not appear to have gone through. Could anyone give me any pointers as to what is going wrong?

**Comment by DilumAluthge** [comment]
Did you install the JuliaRegistrator GitHub app on the new organization?
