### ISSUE TITLE
Need more helpful instructions for error after package changes organizations

### ISSUE THREAD

**Issue by eford** [JuliaRegistries/General#66500]
I'm trying to update a registered package after it changed organizations and get the following message (see [here](https://github.com/JuliaPluto/PlutoTeachingTools.jl/commit/d8c54c4153b87a2af4407967e25593fd14ee36cc
)).
"Error while trying to register: Changing package repo URL not allowed, please submit a pull request with the URL change to the target registry and retry."
I don't see any documentation on how to do that.

**Comment by eford** [comment]
I tried something (https://github.com/JuliaRegistries/General/pull/66501) but have zero confidence that is what I should be doing.

**Comment by DilumAluthge** [comment]
Is the existing documentation (https://github.com/JuliaRegistries/General#how-do-i-transfer-a-package-to-an-organization-or-another-user) sufficient, or should we add more detail?

**Comment by eford** [comment]
That's what I found and tried to act on.  I guess we'll see if it was specific enough for me to get it right the first time.  
If the JuliaRegistrator error message were to provide a link to that, I think that would be an improvement.  As is, I first read documentation at https://github.com/JuliaRegistries/Registrator.jl , but found nothing useful.  Only after googling and trying a few pages did I find that link.

**Comment by DilumAluthge** [comment]
You did indeed do https://github.com/JuliaRegistries/General/pull/66501 correctly.

**Comment by DilumAluthge** [comment]
Perhaps we should add a sentence to https://github.com/JuliaRegistries/Registrator.jl/blob/master/README.md (maybe near the top) that provides a link to the General registry README?

@eford Want to make a PR?

**Comment by eford** [comment]
Sure.  See PR https://github.com/JuliaRegistries/Registrator.jl/pull/383
