### ISSUE TITLE
new package --> new contributor??

### ISSUE THREAD

**Issue by aumpierre-unb** [JuliaRegistries/General#67047]
Hi, I am trying to register a new package (#66536). It passed all checks. As I understand, according to the automatic messages I should first be a contributor, and then have the packages registered. Is it correct? If so, is it of the interest of the community to register this package? I am lost here, need instructions please. Thanks.

**Comment by AshlinHarris** [comment]
My guess is, based the [error message](https://github.com/JuliaRegistries/General/pull/66536#issuecomment-1227181772) and not seeing you as a collaborator on [your repo](https://github.com/aumpierre-unb/InternalFluidFlow.jl), that you would just need to go to the repo settings and add yourself as a public member in the "Collaborators and Teams" section.

After that, I think another call to @JuliaRegistrator register() will move things along. But honestly, I've never seen this issue before.

**Comment by AshlinHarris** [comment]
Sorry, scratch that. The last error message that shows up in (#66536) is just from putting the call to JuliaRegistrator inside a thread on JuliaRegistries (like what I did unintentionally just now). I think you've already taken care of any issues, so just make the call to JuliaRegistrator on the issue thread of your own package. Then, it's just a matter of waiting 3 days for your package to be automatically merged to General.

**Comment by aumpierre-unb** [comment]
Ok, thank you dude! I'll keep trying, it is tricky...

**Comment by DilumAluthge** [comment]
There is no need for you to be a collaborator on the `JuliaRegistries/General` repo in order to register a package.

To update a registration, you don't comment @JuliaRegistrator on any PRs or issues in the `JuliaRegistries/General` repo. Instead, you would go to your package's repo and comment @JuliaRegistrator on the desired commit in your package's repo.

**Comment by DilumAluthge** [comment]
Also, please note that if you post a comment on a PR in the `JuliaRegistries/General` repo, that comment will block auto-merging of the PR unless you edit your comment and add the text `[noblock]`. This is covered in the README: https://github.com/JuliaRegistries/General/blob/master/README.md#automerge-is-blocked-by-one-of-my-comments-how-do-i-unblock-it
