### ISSUE TITLE
Failing to register due to wrong version chosen for  libblastrampoline_jll

### ISSUE THREAD

**Issue by andreasvarga** [JuliaRegistries/General#68456]
I tried to register a new version (0.4.2) of [PeriodicSystems.jl,](https://github.com/andreasvarga/PeriodicSystems.jl) but the registering procedure failed by tring to include a wrong version of libblastrampoline_jll  (5.1.1 indicated as the only possible version although in Project.toml libblastrampoline_jll = "3.0.4" is set in the dependencies under Julia 1.7). The error message from the CI.log  is:

```
[ Info: Attempting to `Pkg.add` package...
    Updating registry at `/tmp/jl_EcQ2LU/registries/General`
┌ Error: Some registries failed to update:
│     — `/tmp/jl_EcQ2LU/registries/General` — registry dirty
└ @ Pkg.Registry /cache/build/default-amdci5-0/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/Pkg/src/Registry/Registry.jl:449
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package libblastrampoline_jll [8e850b90]:
 libblastrampoline_jll [8e850b90] log:
 ├─possible versions are: 5.1.1 or uninstalled
 └─found to have no compatible versions left with PeriodicSystems [5decd0d0]
   └─PeriodicSystems [5decd0d0] log:
     ├─possible versions are: 0.1.0-0.4.2 or uninstalled
     └─restricted to versions 0.4.2 by an explicit requirement, leaving only versions 0.4.2
```
See CI.log [here](https://github.com/JuliaRegistries/General/actions/runs/3073464173/jobs/4965610363).

**Additional remark:** Due to an issue related to the impossibility to generate wrappers for the SLICOT library for Julia v1.8, I am forced to use version 1.7 for which all tests pass. A PR has been proposed to fix the issue (unfortunately still waiting to be merged, see [#5259](https://github.com/JuliaPackaging/Yggdrasil/pull/5259)) . Even if merged, I am not sure if this will cure the situation.

**Comment by DilumAluthge** [comment]
AutoMerge always runs with the latest stable Julia, which is currently Julia 1.8. If your package does not support Julia 1.8, it will fail AutoMerge, and you will need to request a manual merge.

To request a manual merge, please post in the `#pkg-registration` Slack channel as described here: https://github.com/JuliaRegistries/General/blob/master/README.md#my-pull-request-was-not-approved-for-automatic-merging-what-do-i-do

**Comment by DilumAluthge** [comment]
@ericphanson Perhaps we should add this to the FAQs in the README?
