### ISSUE TITLE
Consider propagating upper bounds backwards

### ISSUE THREAD

**Issue by timholy** [JuliaRegistries/General#6910]
Now that upper bounds are getting to be commonplace, it may be worth contemplating propagating the bounds to earlier versions. I am aware that this is scary, but so is not doing it: https://github.com/JuliaGraphics/ColorTypes.jl/pull/143

**Comment by fredrikekre** [comment]
Have you seen https://github.com/bcbi/RetroCap.jl?

**Comment by DilumAluthge** [comment]
Personally, I believe that we should add upper bounds to the earlier versions of our packages in the registry. But I don’t think that currently there is a lot of support for this plan.

In the meantime, you can use RetroCap to do it for all packages in one or more GitHub orgs.

**Comment by timholy** [comment]
Looks like RetroCap will do the job for us, definitely a star-worthy package!

I am traveling for the next couple of days so will wait to tackle this until I can deal with any fallout :smile: .
