### ISSUE TITLE
Are packages with British spelling disallowed (they should)

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaRegistries/General#70112]
I just noticed Humanize.jl and I think it would be bad for the ecosystem if some ended with -ise, or other British endings (also competing Humanise.jl package would also be confusing).

Maybe add some spelling rules in docs, and a way to flag known British, e.g. -our (colour), if not already done? Exceptions could be allowed through though.

I did fix the typo in the title (and it's only a typo, I checked disalowed isn't legal British or US, though some words do have only one l or t.]

https://en.wikipedia.org/wiki/American_and_British_English_spelling_differences#Doubled_consonants

**Comment by fredrikekre** [comment]
People can spell their package names however they like. The existing name similarity check would most likely find Humanize vs Humanise.
