### ISSUE TITLE
No warning for meaningless compat entry

### ISSUE THREAD

**Issue by travigd** [JuliaRegistries/General#7146]
https://github.com/JuliaRegistries/General/pull/7046

To register WebIO v0.8.13 (lucky number 13!), I added JSExpr to the compat because I was trying to fix an issue where JSExpr v1 has just been released and was incompatible.

~The merge bot yelled at me because I didn't have compat for other things so I decided to also add everything else. However, it looks like when I re-triggered the merge bot, it lost the compat entry for JSExpr?~

JSExpr v0.5 depends on WebIO, but in v1.0, we dropped the dependency (and were planning on reversing it for WebIO v1.0). I forgot that WebIO doesn't actually depend on JSExpr though when I added the compat entry.

The registrator bot should probably(?) yell at me because JSExpr is not a dependency of WebIO (which I discovered with #7145).

**Comment by DilumAluthge** [comment]
There was no warning because there was no such compat entry. If you look at https://github.com/JuliaRegistries/General/pull/7046/files, you see that no compat entry was added for `JSExpr`.

So why would there be any warning? Unless I am misunderstanding, there is nothing to warn about.

**Comment by travigd** [comment]
This might actually belong the the JuliaRegistrator repo. There should be a warning in the resulting GitHub comment or PR even though it doesn't make it into the code changes of the PR itself.

**Comment by DilumAluthge** [comment]
I took another look at your Project.toml file. You have a compat entry for JSExpr. However, JSExpr is listed as a test-dependency. It is perfectly normal to have compat entries for test-dependencies. So I’m not sure Registrator would throw a warning either.

**Comment by DilumAluthge** [comment]
But information about test-dependencies is never put into the General registry.

So this all seems like the normal expected behavior

**Comment by travigd** [comment]
Bleh you are indeed correct.

WebIO's tests are in general not great™ with lots of reverse dependencies.

Thanks for your time and I suppose this can be closed.
