### ISSUE TITLE
Delete registery for "CommonHighlight"

### ISSUE THREAD

**Issue by Rratic** [JuliaRegistries/General#71744]
repo: https://github.com/JuliaRoadmap/CommonHighlight.jl

I'm quite busy and won't be able to work on it (and it's obvious it has been deserted for long), and there's already a package mapping the classical highlight.js, which lowers its importance. Since it's totally not useable, I guess no one has ever installed it (you can check the data probably), so it would be fine to delete this.

**Comment by fredrikekre** [comment]
The registry is immutable, but you can indicate in your repository README about the status.
