### ISSUE TITLE
Manual PR for a package that moved to a subdir in a repository?

### ISSUE THREAD

**Issue by tpoisot** [JuliaRegistries/General#73177]
I'm going to release new versions for packages that used to live in different repos, but are now together (in different directories).

The registrator bot refuses to do the PR (which makes sense), but I'm not sure as to how I should update the `Package.toml` when doing the PR myself. I checked https://pkgdocs.julialang.org/v1/toml-files/#Project.toml, but there isn't a mention of how to specify a `subdir` in the docs.

This looks like it's possible because we can have a `subdir` argument to `Pkg.add` (https://pkgdocs.julialang.org/v1/managing-packages/#Adding-a-package-in-a-subdirectory-of-a-repository)é

Is this feasible, and if so what do I need to add to the `Package.toml` in the registry to make it happen?

**Comment by tpoisot** [comment]
After scouring the registry for example, it turns out that `Package.toml` can take a `subdir` argument. AFAIK this isn't documented, what would be the best place to make a PR?

**Comment by JeffFessler** [comment]
Maybe to the README because all the docs in this repo are there (other than what is in the julia manual itself).  Just my guess - I'm not a maintainer.

**Comment by ericphanson** [comment]
> The registrator bot refuses to do the PR  

Registrator.jl can do registrations with subdir packages! But it needs a `subdir` argument. See https://github.com/JuliaRegistries/Registrator.jl#registering-a-package-in-a-subdirectory
