### ISSUE TITLE
Package registration CI for new version stuck

### ISSUE THREAD

**Issue by VEZY** [JuliaRegistries/General#74098]
My package registration #74031 is stuck, with this message for the CI:
> CI (1, ubuntu-latest, x64) Expected — Waiting for status to be reported
Required
> CI (1.3, ubuntu-latest, x64) Expected — Waiting for status to be reported
Required
> CI (1.4, ubuntu-latest, x64) Expected — Waiting for status to be reported
Required

I see that other packages that are registering a new version have the same issue too:  #74053, #74055, #74043, #74042

I don't know if it has something to do with that, but I registered using the [new github action proposed in PackageTemplates](https://juliaci.github.io/PkgTemplates.jl/stable/user/#PkgTemplates.RegisterAction).

**Comment by giordano** [comment]
https://www.githubstatus.com/incidents/4p7zympgsr86

**Comment by VEZY** [comment]
OK thanks, sorry for the issue then.
