### ISSUE TITLE
Clearer when-to-register criteria

### ISSUE THREAD

**Issue by Rratic** [JuliaRegistries/General#74283]
Here's the original comment:

https://github.com/itsdfish/JokerJailBreak.jl/issues/1#issuecomment-1356193634

I don't know how many packages have sneaked in the registery, but it could be necessary, I guess.

**Comment by DilumAluthge** [comment]
Here is what the General registry README currently says:

https://github.com/JuliaRegistries/General/blob/aedbcb2b258933cd17b8e73c1c0a9ad03a913961/README.md?plain=1#L93-L122

I think this covers your question, right? Are there specific questions that you have that are not answered by the above? Or specific information that you'd like us to add to the README?
