### ISSUE TITLE
Manual Merge

### ISSUE THREAD

**Issue by itsdfish** [JuliaRegistries/General#75230]
Hi, 

I was wondering if someone can manually merge https://github.com/JuliaRegistries/General/pull/74118. I received an error, saying version 0.3.0 was already registered (which was not true). I attempted to bypass the issue by incrementing to version 0.3.1, but that lead to a merger failure due to version skipping. 

Thanks for your help.

**Comment by fredrikekre** [comment]
The problem is the tag here: https://github.com/itsdfish/VisualSearchACTR.jl/tree/v0.3.0
