### ISSUE TITLE
What are the steps to migrate a registered package to an organization?

### ISSUE THREAD

**Issue by juliohm** [JuliaRegistries/General#7555]
I would like to migrate some package that are already registered in the registry to a GitHub organization I've just created. I couldn't find the steps in the README FAQ, could you please confirm that I can just proceed with the normal GitHub steps to migrate, and then later submit a PR here to update the URL?

**Comment by DilumAluthge** [comment]
Yeah just transfer the repo on GitHub, and then make a PR here to change the URL.

**Comment by DilumAluthge** [comment]
(This is assuming that the actual name of the package is unchanged.

**Comment by juliohm** [comment]
Thank you @DilumAluthge , should this be added to README? I can close the issue otherwise.

**Comment by DilumAluthge** [comment]
You can leave it open. It will be closed by #7547 when I merge it tomorrow.
