### ISSUE TITLE
Unsatisfiable requirements detected for package CamiXon [e90a53f3]

### ISSUE THREAD

**Issue by walra356** [JuliaRegistries/General#75968]
The commit [e90a53f3] CamiXon v1.8.4 was successfully automerged with GitHub Actions but I find the commit [e90a53f3] CamiXon v1.8.1 in the general registry. I made a fresh installation of Julia, leaving only my .julia.dev directory on the disk but the registry rebuilds with the old version. 

Pkg.add(Pkg.PackageSpec(;name="CamiXon", version="v1.8.4"))

Unsatisfiable requirements detected for package CamiXon [e90a53f3]:
 CamiXon [e90a53f3] log:
 ├─possible versions are: 0.1.2-1.8.1 or uninstalled
 └─restricted to versions 1.8.4 by an explicit requirement — no versions left

Please advice me.

**Comment by jondeuce** [comment]
I'm having the same issue with my package [`Ignite.jl`](https://github.com/JuliaRegistries/General/pull/75937); after merging, the newest version is still not available even after removing and re-downloading `~/.julia/registries`.

I'm not sure if this is a real issue or not; maybe the general registry is not updated as often as I thought, and I simply need to wait a bit, but I wanted to double check.

**Comment by DilumAluthge** [comment]
There are two "flavors" of the General registry: `conservative` and `eager`. The default flavor is `conservative`.

The conservative flavor is only updated once the Pkg server is ready to serve all packages and artifacts from the new version of the registry.

Usually, the conservative flavor updates pretty quickly after a pull request is merged. However, if some pull requests are merged for packages that have very large artifacts, it can sometimes take a while for the conservative flavor to be updated.

We recommend that most users use the conservative flavor.

However, if you need the very latest version of the registry, and you can't wait for the conservative flavor to update, you can switch to the eager flavor. The instructions for switching to the eager flavor are available here: https://pkgdocs.julialang.org/dev/registries/#Registry-flavors

**Comment by DilumAluthge** [comment]
I'm going to close this issue. However, if you are still able to reproduce this issue after switching to the `eager` flavor, let me know, and I'll reopen this issue.

**Comment by walra356** [comment]
Yes! It took me more than a day before I dropped the issue... You solved it for me in a matter of seconds... Thank you for the support.
