### ISSUE TITLE
Document "mandatory waiting period"

### ISSUE THREAD

**Issue by timholy** [JuliaRegistries/General#7816]
E.g., https://github.com/JuliaRegistries/General/pull/7815. It doesn't seem easy to determine what this period is.

**Comment by DilumAluthge** [comment]
Do you think it would be sufficient to put it in the README? Or does it need to go in the automerge comment?

Btw it’s three days for new packages, everything else is 15 minutes.

**Comment by timholy** [comment]
I think either would be OK. Ideally there would be one place where this number is encoded, both in how its documented and implemented, but that's clearly not essential if it's not easy to achieve.

**Comment by DilumAluthge** [comment]
It’s defined here:
https://github.com/JuliaRegistries/General/blob/5d0611f9c521f0004b9baf7c28ae66ddeacc5f12/.github/workflows/automerge.yml#L27

But that’s not super user friendly

**Comment by timholy** [comment]
Yeah, if one wanted to enforce DRY one would have to parse that and generate the documentation from it. Might be a case where DRY isn't worth it; one could insert comments about the other place(s) that need updating if those numbers change.
