### ISSUE TITLE
Time to start subdividing within letters `S/o/SomePackage.jl` etc

### ISSUE THREAD

**Issue by oxinabox** [JuliaRegistries/General#78672]
We now have [over 1000 packages starting with `S`](https://github.com/JuliaRegistries/General/tree/master/S)
so github will not display the full list.
So we might want to introduce another level into to the folder tree.

**Comment by StefanKarpinski** [comment]
We could change it to a two-letter prefix, which is still only 26^2 = 676 prefixes, which GitHub will list.

**Comment by KristofferC** [comment]
Or we can start by moving jlls to their own `jll` top-level folder. `jll/S/SBML_jll` for example.

**Comment by StefanKarpinski** [comment]
Ah, that's a good idea too.
