### ISSUE TITLE
Error while trying to register: Changing package repo URL not allowed

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaRegistries/General#8646]
https://github.com/beacon-biosignals/ElectronTests.jl/commit/0f40b67fb0ba06a1cc494ff3b76ae2bb9182a02b#commitcomment-37035716

I already did change the URL:

https://github.com/JuliaRegistries/General/blob/master/E/ElectronTests/Package.toml

Did I mess it up, or what's going on?

**Comment by fredrikekre** [comment]
Missing `.git`?

**Comment by DilumAluthge** [comment]
https://github.com/JuliaRegistries/General/pull/8647

**Comment by SimonDanisch** [comment]
Oh...good catch! Hopefully that fixes it! :) 
Thanks for the fast reply!

**Comment by SimonDanisch** [comment]
Yay, finally: https://github.com/JuliaRegistries/General/pull/8652! Thanks everyone!
