### ISSUE TITLE
ERROR: SystemError: opening file "..." : Permission denied

### ISSUE THREAD

**Issue by lchris17** [JuliaRegistries/General#9302]
Hey there,
I'm having an issue adding Julia to anaconda. After downloading I give the commands;

using Pkg
Pkg.add("IJulia")

It seems like it will download but then it smacks me with this error. I have tried running the executable as administrator but I have not had any luck.

**Comment by fredrikekre** [comment]
This issue does not belong here, open at the IJulia repo, or perhaps better post it as a question to https://discourse.julialang.org/
