### ISSUE TITLE
Not able to register because of lack of upper-bound for releases of LinearAlgebra

### ISSUE THREAD

**Issue by andreasvarga** [JuliaRegistries/General#94164]
I tried to register a new version of MatrixEquations (see [here](https://github.com/JuliaRegistries/General/pull/94157)), but
the AutoMerge was not performed because of:

"The following dependencies do not have a [compat] entry that is upper-bounded and only includes a finite number of breaking releases: LinearAlgebra"

Looking into thee Project.toml files of several packages, there is no upper-bounding for LinearAlgebra in any of them. I registered a new release recently, without problems. If this bounding issue is new, what I have to put in compat for LinearAlgebra? LinearAlgebra has no registered releases (see [here](https://github.com/JuliaLang/LinearAlgebra.jl))! Thanks in advance for help.

**Comment by DilumAluthge** [comment]
Cross-ref https://discourse.julialang.org/t/psa-compat-requirements-in-the-general-registry-are-changing/104958?u=dilumaluthge

**Comment by DilumAluthge** [comment]
@vchuravy What would be a reasonable value for someone to put as the initial compat entry for LinearAlgebra?

**Comment by vchuravy** [comment]
I think "1" is alway okay.

**Comment by andreasvarga** [comment]
I performed the above correction and trigered again the Registrator. Everything seems to be OK (see https://github.com/JuliaRegistries/General/pull/94157) , but merging still doesn't occur. I wonder what I have to do to finish.

**Comment by vchuravy** [comment]
You wrote noblock instead of [noblock]. I edited and it should go through now

**Comment by andreasvarga** [comment]
Thanks.
