### ISSUE TITLE
Add CI jobs for Julia v1.10

### ISSUE THREAD

**Issue by giordano** [JuliaRegistries/General#97766]
Now that Julia v1.10 is out, we want to add CI jobs for this minor version.  Look at the changes in #97765 for the jobs we want to touch.  However we're currently blocked on not having an up-to-date manifest for Julia v1.10: https://github.com/JuliaRegistries/General/pull/95226#issuecomment-1869790342.

CC: @DilumAluthge.

**Comment by DilumAluthge** [comment]
Fixed by https://github.com/JuliaRegistries/General/pull/98052

**Comment by willow-ahrens** [comment]
is this related to https://github.com/julia-actions/julia-buildpkg/issues/48?

**Comment by giordano** [comment]
No, PkgServer is just unhappy today.
